/*
 * LevelUp — alle demo-data op één plek.
 *
 * Alles hier is verzonnen: het gezin Janssens, hun rekeningen en transacties bestaan niet.
 * Bedragen zijn vereenvoudigd en dienen enkel ter illustratie (geen financieel advies).
 * Wat tijdens de demo verandert (XP, voltooide missies, ouderinstellingen) staat niet hier
 * maar in localStorage — zie js/app.js.
 */

/* ---------- Geldonderwerpen en niveaus ---------- */

const TOPICS = [
  { id: 'betalen', label: 'Betalen', short: 'Betalen', emoji: '💳' },
  { id: 'sparen', label: 'Sparen', short: 'Sparen', emoji: '🐷' },
  { id: 'budget', label: 'Budget & geld', short: 'Budget', emoji: '📊' },
  { id: 'abonnementen', label: 'Abonnementen', short: 'Abo’s', emoji: '🔁' },
  { id: 'beleggen', label: 'Beleggen', short: 'Beleggen', emoji: '📈' },
  { id: 'loon', label: 'Loon & werk', short: 'Loon', emoji: '💼' },
  { id: 'huur', label: 'Huren & wonen', short: 'Wonen', emoji: '🏠' },
  { id: 'lenen', label: 'Lenen & schulden', short: 'Lenen', emoji: '🧾' },
];

// XP-drempels per onderwerp.
const LEVELS = [
  { level: 1, name: 'Starter', minXp: 0 },
  { level: 2, name: 'Ontdekker', minXp: 100 },
  { level: 3, name: 'Kenner', minXp: 250 },
  { level: 4, name: 'Pro', minXp: 450 },
  { level: 5, name: 'Expert', minXp: 700 },
];

// Drempels voor het totaalniveau (som van alle onderwerpen).
const TOTAL_LEVELS = [
  { level: 1, name: 'Geldstarter', minXp: 0 },
  { level: 2, name: 'Geldontdekker', minXp: 600 },
  { level: 3, name: 'Geldkenner', minXp: 1400 },
  { level: 4, name: 'Geldpro', minXp: 2600 },
  { level: 5, name: 'Geldexpert', minXp: 4000 },
];

// De "Wat als ik…?"-simulator gaat pas open vanaf deze leeftijd.
const SIMULATOR_MIN_AGE = 14;

// Kalenderweek van de laatste waarde in weeklyXp (30 september 2026 = week 40).
const CURRENT_WEEK = 40;

const TX_CATEGORIES = {
  zakgeld: { label: 'Zakgeld', emoji: '💶' },
  loon: { label: 'Loon', emoji: '💼' },
  bijverdienste: { label: 'Bijverdienste', emoji: '🧸' },
  cadeau: { label: 'Cadeau', emoji: '🎁' },
  sparen: { label: 'Sparen', emoji: '🐷' },
  abonnement: { label: 'Abonnement', emoji: '🔁' },
  eten: { label: 'Eten & snacks', emoji: '🥪' },
  kleding: { label: 'Kleding', emoji: '👕' },
  vrijetijd: { label: 'Vrije tijd', emoji: '🎬' },
  gaming: { label: 'Gaming', emoji: '🎮' },
  telefoon: { label: 'Telefoon', emoji: '📱' },
  snoep: { label: 'Snoep', emoji: '🍬' },
};

/* ---------- Het gezin ---------- */

const PARENT = { id: 'sofie', name: 'Sofie', fullName: 'Sofie Janssens', emoji: '👩' };

// Lena's gemiddelde schoolmaand (september), afgeleid van haar transacties hieronder.
// Dit is het vertrekpunt ("Nu") van elke simulatie.
const LENA_NOW = {
  income: [
    { label: 'Zakgeld', amount: 50 },
    { label: 'Oppassen', amount: 35 },
  ],
  expenses: [
    { label: 'Abonnementen', amount: 28.97 },
    { label: 'Eten & snacks', amount: 18.6 },
    { label: 'Telefoon', amount: 10 },
    { label: 'Kleding (achteraf betalen)', amount: 13.32 },
    { label: 'Sparen', amount: 10, save: true },
  ],
};

const CHILDREN = {
  lena: {
    id: 'lena',
    lastName: 'Janssens',
    emoji: '👧',
    age: 16,
    birthDate: '2010-07-12',
    customerSince: 'juli 2022',
    account: { type: 'Jongerenrekening', iban: 'BE00 7310 1234 5616', balance: 186.4 },
    savings: { type: 'Spaarrekening', balance: 640 },
    streak: 5,
    missionsCompletedBefore: 23,
    defaults: {
      name: 'Lena',
      school: 'Sint-Jozefscollege — 5de middelbaar',
      city: 'Hasselt',
      allowance: 50,
      allowanceFrequency: 'maand',
      autoSave: 10,
      weeklyLimit: 40,
      onlinePayments: true,
      inAppPurchases: true,
      lockedTopics: [],
      focusTopic: 'abonnementen',
      reward: '€5 extra zakgeld bij elk nieuw niveau',
    },
    moneyType: {
      title: 'De genieter met een plan 🎯',
      text: 'Je geniet graag van muziek, series en snacks, maar je spaart ook automatisch en zette meteen €200 van je zomerloon opzij. Volgende stap: je vaste kosten onder controle houden.',
    },
    baseXp: { betalen: 310, sparen: 380, budget: 180, abonnementen: 220, beleggen: 60, loon: 240, huur: 90, lenen: 70 },
    xp4WeeksAgo: { betalen: 230, sparen: 260, budget: 90, abonnementen: 150, beleggen: 20, loon: 90, huur: 40, lenen: 30 },
    weeklyXp: [85, 120, 60, 140, 95, 40],
    signals: {
      betalen: [
        { tone: 'good', text: 'Je betaalt vlot met kaart en smartphone — geen geweigerde betalingen.' },
        { tone: 'info', text: 'Je eerste online aankoop (ModeMix) deed je in augustus.' },
      ],
      sparen: [
        { tone: 'good', text: 'Sinds september gaat er elke maand automatisch €10 naar je spaarrekening.' },
        { tone: 'good', text: 'Na je eerste loon zette je meteen €200 opzij.' },
      ],
      budget: [
        { tone: 'warn', text: 'In september ging €80,89 van je €85 inkomen op.' },
        { tone: 'warn', text: '7 snackaankopen op school in september: samen €18,60.' },
      ],
      abonnementen: [
        { tone: 'warn', text: 'Disney+ loopt sinds augustus automatisch door na een gratis proef.' },
        { tone: 'info', text: '3 abonnementen = €28,97 per maand.' },
      ],
      beleggen: [{ tone: 'info', text: 'Nog geen ervaring — oefen eerst in de simulator.' }],
      loon: [{ tone: 'good', text: 'Eerste studentenjob: 2 maanden loon van IJssalon Gelato.' }],
      huur: [{ tone: 'info', text: 'Je woont nog thuis — nog geen vaste woonkosten.' }],
      lenen: [{ tone: 'warn', text: 'Kleding gekocht met “achteraf betalen”: nog 1 termijn open (€13,31 in oktober).' }],
    },
    goals: [
      { name: 'Interrail met vrienden', emoji: '🚆', target: 450, saved: 210 },
      { name: 'Eerste rijlessen', emoji: '🚗', target: 600, saved: 60 },
    ],
    badges: [
      { emoji: '🐷', name: 'Eerste spaardoel', desc: 'Maakte een spaardoel aan', earned: true },
      { emoji: '💼', name: 'Eerste loon', desc: 'Ontving een eerste studentenloon', earned: true },
      { emoji: '🔥', name: '5 dagen op rij', desc: 'Elke dag een geldmissie gespeeld', earned: true },
      { emoji: '🕵️', name: 'Abonnementen-detective', desc: 'Rekende de abonnementen per jaar uit', unlockMission: 'l-abo' },
      { emoji: '🛡️', name: 'Phishing-proof', desc: 'Herkende een valse betaal-sms', unlockMission: 'l-betalen' },
      { emoji: '🧾', name: 'Loonstrook-lezer', desc: 'Snapt het verschil tussen bruto en netto', unlockMission: 'l-loon' },
      { emoji: '🏠', name: 'Kotklaar', desc: 'Simuleerde studeren of alleen wonen', unlockScenario: ['studeren', 'huren'] },
      { emoji: '🔭', name: 'Toekomstdenker', desc: 'Vergeleek sparen en beleggen', unlockScenario: ['beleggen'] },
    ],
    transactions: [
      { id: 'l01', date: '2026-07-01', desc: 'Zakgeld — Sofie Janssens', amount: 50, cat: 'zakgeld' },
      { id: 'l02', date: '2026-07-03', desc: 'Spotify Premium', amount: -10.99, cat: 'abonnement' },
      { id: 'l03', date: '2026-07-05', desc: 'Netflix', amount: -7.99, cat: 'abonnement' },
      { id: 'l04', date: '2026-07-12', desc: 'Verjaardag — oma Mariette', amount: 50, cat: 'cadeau' },
      { id: 'l05', date: '2026-07-15', desc: 'Frituur ’t Pleintje', amount: -8.5, cat: 'eten' },
      { id: 'l06', date: '2026-07-22', desc: 'Bioscoop Hasselt', amount: -12.5, cat: 'vrijetijd' },
      { id: 'l07', date: '2026-07-31', desc: 'Loon juli — IJssalon Gelato', amount: 312.4, cat: 'loon' },
      { id: 'l08', date: '2026-08-01', desc: 'Zakgeld — Sofie Janssens', amount: 50, cat: 'zakgeld' },
      { id: 'l09', date: '2026-08-02', desc: 'Naar spaarrekening — Interrail', amount: -200, cat: 'sparen' },
      { id: 'l10', date: '2026-08-03', desc: 'Spotify Premium', amount: -10.99, cat: 'abonnement' },
      { id: 'l11', date: '2026-08-05', desc: 'Netflix', amount: -7.99, cat: 'abonnement' },
      { id: 'l12', date: '2026-08-09', desc: 'Disney+ (einde gratis proef)', amount: -9.99, cat: 'abonnement' },
      { id: 'l13', date: '2026-08-14', desc: 'ModeMix — achteraf betalen (termijn 1/3)', amount: -13.32, cat: 'kleding' },
      { id: 'l14', date: '2026-08-18', desc: 'Bioscoop Hasselt', amount: -12.5, cat: 'vrijetijd' },
      { id: 'l15', date: '2026-08-22', desc: 'Game-aankoop (in-game munten)', amount: -8.99, cat: 'gaming' },
      { id: 'l16', date: '2026-08-31', desc: 'Loon augustus — IJssalon Gelato', amount: 356.8, cat: 'loon' },
      { id: 'l17', date: '2026-09-01', desc: 'Zakgeld — Sofie Janssens', amount: 50, cat: 'zakgeld' },
      { id: 'l18', date: '2026-09-01', desc: 'Naar spaarrekening (automatisch)', amount: -10, cat: 'sparen' },
      { id: 'l19', date: '2026-09-02', desc: 'Broodjeszaak De Pauze', amount: -3.2, cat: 'eten' },
      { id: 'l20', date: '2026-09-03', desc: 'Spotify Premium', amount: -10.99, cat: 'abonnement' },
      { id: 'l21', date: '2026-09-04', desc: 'Drankautomaat school', amount: -2.5, cat: 'eten' },
      { id: 'l22', date: '2026-09-05', desc: 'Netflix', amount: -7.99, cat: 'abonnement' },
      { id: 'l23', date: '2026-09-09', desc: 'Disney+', amount: -9.99, cat: 'abonnement' },
      { id: 'l24', date: '2026-09-09', desc: 'Bakkerij Korenaar', amount: -2.8, cat: 'eten' },
      { id: 'l25', date: '2026-09-11', desc: 'Drankautomaat school', amount: -2.5, cat: 'eten' },
      { id: 'l26', date: '2026-09-14', desc: 'ModeMix — achteraf betalen (termijn 2/3)', amount: -13.32, cat: 'kleding' },
      { id: 'l27', date: '2026-09-16', desc: 'Broodjeszaak De Pauze', amount: -3.2, cat: 'eten' },
      { id: 'l28', date: '2026-09-19', desc: 'Oppassen — fam. Claes', amount: 35, cat: 'bijverdienste' },
      { id: 'l29', date: '2026-09-23', desc: 'Drankautomaat school', amount: -2.1, cat: 'eten' },
      { id: 'l30', date: '2026-09-25', desc: 'Bakkerij Korenaar', amount: -2.3, cat: 'eten' },
      { id: 'l31', date: '2026-09-26', desc: 'Herlaadkaart gsm', amount: -10, cat: 'telefoon' },
    ],
    monthlyNow: LENA_NOW,
    activity: [
      { at: '2026-09-29', emoji: '✅', text: 'Missie “Contactloos betalen” voltooid (+40 XP)' },
      { at: '2026-09-27', emoji: '🎉', text: 'Haalde niveau 3 in Betalen' },
      { at: '2026-09-24', emoji: '🏅', text: 'Kreeg de badge “5 dagen op rij” 🔥' },
      { at: '2026-09-20', emoji: '✅', text: 'Missie “Wat is rente?” voltooid (+50 XP)' },
      { at: '2026-08-02', emoji: '🐷', text: 'Startte het spaardoel “Interrail met vrienden”' },
    ],
    parentInsights: [
      {
        tone: 'warn',
        title: 'Abonnement na gratis proef',
        text: 'Bij {name} loopt Disney+ sinds augustus automatisch door (€9,99 per maand). Samen met Spotify en Netflix is dat ± €348 per jaar.',
        tip: 'Gespreksstarter: “Welk abonnement zou jij als eerste schrappen?”',
      },
      {
        tone: 'warn',
        title: 'Achteraf betalen',
        text: 'Er staat nog 1 termijn open voor kleding (€13,31 in oktober).',
        tip: 'Leg uit dat achteraf betalen eigenlijk lenen is.',
      },
      {
        tone: 'good',
        title: 'Sterke spaarder',
        text: '{name} zette €200 van het zomerloon opzij en spaart sinds september automatisch.',
        tip: 'Een compliment waard!',
      },
    ],
  },

  mats: {
    id: 'mats',
    lastName: 'Janssens',
    emoji: '👦',
    age: 11,
    birthDate: '2015-02-03',
    customerSince: 'februari 2023',
    account: { type: 'Jongerenrekening', iban: 'BE00 7310 1234 5611', balance: 23.4 },
    savings: { type: 'Spaarrekening', balance: 35 },
    streak: 2,
    missionsCompletedBefore: 9,
    defaults: {
      name: 'Mats',
      school: 'Basisschool De Regenboog — 6de leerjaar',
      city: 'Hasselt',
      allowance: 20,
      allowanceFrequency: 'maand',
      autoSave: 5,
      weeklyLimit: 10,
      onlinePayments: false,
      inAppPurchases: true,
      lockedTopics: ['beleggen', 'lenen'],
      focusTopic: 'sparen',
      reward: 'Samen pannenkoeken bakken 🥞',
    },
    moneyType: {
      title: 'De trouwe spaarder 🐷',
      text: 'Je spaart elke maand voor je game, maar Robux en snoep eten een flink stuk van je zakgeld op.',
    },
    baseXp: { betalen: 120, sparen: 260, budget: 90, abonnementen: 30, beleggen: 0, loon: 10, huur: 0, lenen: 0 },
    xp4WeeksAgo: { betalen: 80, sparen: 200, budget: 40, abonnementen: 30, beleggen: 0, loon: 10, huur: 0, lenen: 0 },
    weeklyXp: [30, 45, 20, 60, 35, 15],
    signals: {
      betalen: [{ tone: 'warn', text: '3 keer Robux gekocht in september (€14,97).' }],
      sparen: [{ tone: 'good', text: 'Spaart elke maand automatisch €5 voor een nieuwe game.' }],
      budget: [{ tone: 'warn', text: 'Vorige week €6 aan snoep: bijna een derde van je zakgeld.' }],
      abonnementen: [{ tone: 'info', text: 'Nog geen abonnementen op je naam.' }],
      beleggen: [{ tone: 'info', text: 'Wordt interessant als je wat ouder bent.' }],
      loon: [{ tone: 'good', text: 'Verdiende €10 met auto wassen bij opa.' }],
      huur: [{ tone: 'info', text: 'Nog niet aan de orde — geniet ervan!' }],
      lenen: [{ tone: 'info', text: 'Nog geen schulden, goed zo!' }],
    },
    goals: [{ name: 'Nieuwe videogame', emoji: '🎮', target: 59.99, saved: 35 }],
    badges: [
      { emoji: '🐷', name: 'Spaarpot-starter', desc: 'Eerste automatische spaaropdracht', earned: true },
      { emoji: '⭐', name: 'Eerste week', desc: '7 dagen LevelUp gespeeld', earned: true },
      { emoji: '🎯', name: 'Doelzoeker', desc: 'Berekende wanneer het spaardoel gehaald is', unlockMission: 'm-sparen' },
      { emoji: '🎮', name: 'Robux-rekenaar', desc: 'Weet hoeveel echt geld in-game munten kosten', unlockMission: 'm-betalen' },
      { emoji: '🍬', name: 'Snoepbaas', desc: 'Rekende uit wat snoep per maand kost', unlockMission: 'm-budget' },
    ],
    transactions: [
      { id: 'm01', date: '2026-08-01', desc: 'Zakgeld — Sofie Janssens', amount: 20, cat: 'zakgeld' },
      { id: 'm02', date: '2026-09-01', desc: 'Zakgeld — Sofie Janssens', amount: 20, cat: 'zakgeld' },
      { id: 'm03', date: '2026-09-01', desc: 'Naar spaarrekening (automatisch)', amount: -5, cat: 'sparen' },
      { id: 'm04', date: '2026-09-06', desc: 'Roblox — Robux', amount: -4.99, cat: 'gaming' },
      { id: 'm05', date: '2026-09-10', desc: 'Dagbladhandel De Hoek', amount: -2.5, cat: 'snoep' },
      { id: 'm06', date: '2026-09-13', desc: 'Roblox — Robux', amount: -4.99, cat: 'gaming' },
      { id: 'm07', date: '2026-09-15', desc: 'Dagbladhandel De Hoek', amount: -1.8, cat: 'snoep' },
      { id: 'm08', date: '2026-09-17', desc: 'Dagbladhandel De Hoek', amount: -1.7, cat: 'snoep' },
      { id: 'm09', date: '2026-09-20', desc: 'Auto wassen — opa Jef', amount: 10, cat: 'bijverdienste' },
      { id: 'm10', date: '2026-09-24', desc: 'Roblox — Robux', amount: -4.99, cat: 'gaming' },
    ],
    monthlyNow: null,
    activity: [
      { at: '2026-09-28', emoji: '✅', text: 'Missie “Wat is een spaarrekening?” voltooid (+30 XP)' },
      { at: '2026-09-21', emoji: '🎉', text: 'Haalde niveau 3 in Sparen' },
      { at: '2026-09-14', emoji: '🏅', text: 'Kreeg de badge “Spaarpot-starter” 🐷' },
    ],
    parentInsights: [
      {
        tone: 'warn',
        title: 'In-app aankopen',
        text: '{name} kocht 3 keer Robux in september (€14,97 — bijna 75% van het zakgeld).',
        tip: 'Overweeg in-app aankopen uit te zetten of een lagere weeklimiet in te stellen.',
      },
      {
        tone: 'good',
        title: 'Trouwe spaarder',
        text: '{name} spaart elke maand €5 voor een nieuwe game.',
        tip: 'Beloon het doorzetten, bv. met een extra euro als het doel gehaald is.',
      },
    ],
  },
};

/* ---------- Missies: quizvragen op basis van de eigen transacties ---------- */

const MISSIONS = [
  {
    id: 'l-abo',
    child: 'lena',
    topic: 'abonnementen',
    title: 'Abonnementen-check',
    txIds: ['l20', 'l22', 'l23'],
    context: 'Samen €28,97 per maand. Disney+ begon in augustus als gratis proef en loopt nu gewoon door.',
    question: 'Hoeveel betaal je per jaar aan deze 3 abonnementen?',
    options: ['± €87', '± €174', '± €348', '± €521'],
    correct: 2,
    explanation: '€28,97 × 12 = €347,64 per jaar. Tip: zet een herinnering vóór een gratis proef afloopt, en check één keer per maand welke abonnementen je echt gebruikt.',
    xp: 60,
  },
  {
    id: 'l-budget',
    child: 'lena',
    topic: 'budget',
    title: 'Snacks op school',
    txIds: ['l19', 'l21', 'l24', 'l25', 'l27', 'l29', 'l30'],
    context: '7 kleine aankopen in september: samen €18,60.',
    question: 'Als je elke schoolmaand zoveel uitgeeft, hoeveel is dat dan op een schooljaar (10 maanden)?',
    options: ['€18,60', '€93', '€186', '€223'],
    correct: 2,
    explanation: '€18,60 × 10 = €186 — bijna de helft van je Interrail-reis! Kleine bedragen tellen snel op. Neem 2 dagen per week iets van thuis mee en je houdt ± €75 per jaar over.',
    xp: 50,
  },
  {
    id: 'l-betalen',
    child: 'lena',
    topic: 'betalen',
    title: 'Een verdachte sms',
    txIds: ['l13'],
    context: 'Je kocht in augustus online kleding. Vandaag krijg je deze sms:',
    sms: 'Je pakket kan niet geleverd worden. Betaal €1,99 extra verzendkosten via pakket-levering.info',
    question: 'Wat doe je?',
    options: [
      'Snel betalen, het is maar €1,99',
      'Niet klikken — ik check mijn bestelling zelf in de app of op de site van de winkel',
      'Mijn kaartgegevens terugsturen per sms',
      'De link doorsturen naar mijn vrienden',
    ],
    correct: 1,
    explanation: 'Dit is phishing: oplichters sturen sms’jes met kleine bedragen om je kaartgegevens te stelen. Klik nooit op betaallinks in een sms; open zelf de app. Twijfel je? Vraag het aan je ouder of aan je bank.',
    xp: 50,
  },
  {
    id: 'l-sparen',
    child: 'lena',
    topic: 'sparen',
    title: 'Hoe lang nog tot Interrail?',
    txIds: ['l09', 'l18'],
    context: 'Spaardoel “Interrail met vrienden”: €210 van de €450 staat al opzij. Elke maand gaat er automatisch €10 bij.',
    question: 'Hoeveel maanden duurt het nog om je doel te halen?',
    options: ['6 maanden', '12 maanden', '24 maanden', '45 maanden'],
    correct: 2,
    explanation: 'Je hebt nog €240 nodig: €240 ÷ €10 = 24 maanden. Zet je daarnaast €20 van je snackgeld opzij (€30 per maand), dan ben je er al na 8 maanden — net op tijd voor de zomer.',
    xp: 50,
  },
  {
    id: 'l-loon',
    child: 'lena',
    topic: 'loon',
    title: 'Je eerste loonstrook',
    txIds: ['l16'],
    context: 'Op je loonstrook van augustus (32 uur gewerkt): bruto €366,74 − solidariteitsbijdrage €9,94 (2,71%) = netto €356,80.',
    question: 'Waar gaan die €9,94 naartoe?',
    options: [
      'Naar je baas',
      'Naar bankkosten',
      'Naar een solidariteitsbijdrage voor de sociale zekerheid',
      'Naar btw op je loon',
    ],
    correct: 2,
    explanation: 'Als jobstudent betaal je een kleine solidariteitsbijdrage van 2,71% (zolang je binnen je studentenuren blijft). Zo betaal je mee aan de sociale zekerheid, zoals ziekenfonds en pensioenen. Bij een gewone job gaan er meer sociale bijdragen (13,07%) en belastingen af.',
    xp: 50,
  },
  {
    id: 'l-huur',
    child: 'lena',
    topic: 'huur',
    title: 'Zakgeld versus kothuur',
    txIds: ['l17'],
    context: 'Een studentenkot in Leuven kost al snel zo’n €475 per maand.',
    question: 'Hoeveel maanden zakgeld heb je nodig voor één maand kothuur?',
    options: ['2 maanden', '5 maanden', '9,5 maanden', '20 maanden'],
    correct: 2,
    explanation: '€475 ÷ €50 = 9,5 maanden zakgeld voor één maand huur! En dan komen er nog eten, energie en een huurwaarborg bij. Speel het scenario “Gaan studeren” om te zien hoe zo’n budget eruitziet.',
    xp: 50,
  },
  {
    id: 'l-lenen',
    child: 'lena',
    topic: 'lenen',
    title: 'Achteraf betalen',
    txIds: ['l13', 'l26'],
    context: 'Je kocht kleding van €39,95 met “achteraf betalen” in 3 termijnen. De laatste termijn (€13,31) komt in oktober.',
    question: 'Wat gebeurt er als je een termijn mist?',
    options: [
      'Niets, achteraf betalen is gratis',
      'Er komen vaak extra kosten bij en het wordt een schuld die kan doorgaan naar een incassobureau',
      'De winkel neemt de kleren gewoon terug',
      'Je bank betaalt het automatisch voor je',
    ],
    correct: 1,
    explanation: 'Achteraf betalen is een vorm van lenen. Mis je een betaling, dan komen er aanmaningskosten bij en kan het bij een incassobureau belanden. Vuistregel: koop alleen “achteraf” wat je nu ook al zou kunnen betalen.',
    xp: 50,
  },
  {
    id: 'l-beleggen',
    child: 'lena',
    topic: 'beleggen',
    title: 'Verjaardagsgeld laten groeien',
    txIds: ['l04'],
    context: 'Stel: je zet elk jaar €50 verjaardagsgeld opzij tot je 26 bent (samen €500). Op een spaarrekening (± 1,5% rente) wordt dat ± €535. Belegd in een gespreid fonds (gemiddeld ± 6% per jaar, niet gegarandeerd) ± €660.',
    question: 'Wat is het grootste verschil tussen sparen en beleggen?',
    options: [
      'Beleggen levert altijd meer op',
      'Beleggen kan meer opbrengen, maar de waarde kan ook dalen',
      'Sparen mag pas vanaf 18 jaar',
      'Er is geen verschil',
    ],
    correct: 1,
    explanation: 'Op een spaarrekening is je geld veilig en krijg je een kleine rente. Bij beleggen koop je een stukje van bedrijven: op lange termijn groeit dat gemiddeld meer, maar het kan ook (tijdelijk) dalen. Spreiden en lang volhouden helpen.',
    xp: 50,
  },
  {
    id: 'm-sparen',
    child: 'mats',
    topic: 'sparen',
    title: 'Sparen voor je game',
    txIds: ['m03'],
    context: 'Je spaardoel: een nieuwe videogame van €59,99. Je hebt al €35 op je spaarrekening.',
    question: 'Hoeveel maanden moet je nog sparen als je €5 per maand opzij zet?',
    options: ['2 maanden', '5 maanden', '12 maanden', '25 maanden'],
    correct: 1,
    explanation: 'Je hebt nog €24,99 nodig, afgerond €25. €25 ÷ €5 = 5 maanden. Zet je €10 per maand opzij, dan heb je je game al na 3 maanden!',
    xp: 50,
  },
  {
    id: 'm-betalen',
    child: 'mats',
    topic: 'betalen',
    title: 'Robux zijn echt geld',
    txIds: ['m04', 'm06', 'm10'],
    context: 'In september kocht je 3 keer Robux.',
    question: 'Hoeveel echt geld was dat samen?',
    options: ['€4,99', '€9,98', '€14,97', '€49,90'],
    correct: 2,
    explanation: '3 × €4,99 = €14,97. Robux voelen als speelgeld, maar je betaalt met echt geld: dat is bijna driekwart van je zakgeld!',
    xp: 50,
  },
  {
    id: 'm-budget',
    child: 'mats',
    topic: 'budget',
    title: 'Snoep per maand',
    txIds: ['m05', 'm07', 'm08'],
    context: 'Vorige week kocht je 3 keer snoep: samen €6.',
    question: 'Hoeveel is dat in een maand (4 weken)?',
    options: ['€6', '€12', '€24', '€60'],
    correct: 2,
    explanation: '€6 × 4 = €24 — dat is meer dan je zakgeld van €20! Kies elke week wat je écht wil, en hou de rest over voor je game.',
    xp: 50,
  },
];

/* ---------- "Wat als ik…?"-scenario's (voor Lena) ---------- */
// "Nu" komt altijd uit LENA_NOW; elke keuze beschrijft het maandbudget "Straks".

const SCENARIOS = [
  {
    id: 'studeren',
    emoji: '🎓',
    title: 'Gaan studeren',
    when: 'Over ± 2 jaar',
    intro: 'Stel: na het middelbaar ga je studeren in Leuven. Wat moet je allemaal regelen, en wat betekent dat voor je maandbudget?',
    keywords: ['studeren', 'studie', 'student worden', 'unief', 'universiteit', 'hogeschool', 'hoger onderwijs', 'kot', 'richting'],
    topics: ['budget', 'huur'],
    xp: 40,
    checklist: [
      'Kies je richting en schrijf je op tijd in',
      'Betaal het inschrijvingsgeld (± €1.200 per jaar, minder met een studietoelage)',
      'Check of je recht hebt op een studietoelage',
      'Beslis: op kot, of thuis wonen en pendelen',
      'Maak samen met je ouders een studentenbudget: wie betaalt wat?',
      'Voorzie een laptop en je cursussen',
    ],
    options: [
      {
        id: 'kot',
        label: '🏠 Op kot in Leuven',
        income: [
          { label: 'Bijdrage ouders', amount: 500 },
          { label: 'Studentenjob', amount: 280 },
        ],
        expenses: [
          { label: 'Kothuur', amount: 475 },
          { label: 'Eten & snacks', amount: 180 },
          { label: 'Studiemateriaal', amount: 35 },
          { label: 'Trein naar huis', amount: 25 },
          { label: 'Abonnementen', amount: 28.97 },
          { label: 'Telefoon', amount: 15 },
          { label: 'Vrije tijd', amount: 40 },
          { label: 'Sparen', amount: 10, save: true },
        ],
        oneTime: [
          { label: 'Inschrijvingsgeld (1ste jaar)', amount: 1200 },
          { label: 'Huurwaarborg kot', amount: 950 },
          { label: 'Laptop', amount: 750 },
          { label: 'Kotspullen', amount: 250 },
        ],
        tip: 'Op kot kom je €28,97 per maand tekort — precies wat je nu aan Spotify, Netflix en Disney+ betaalt. Schrap er één of twee en je budget klopt weer.',
      },
      {
        id: 'pendelen',
        label: '🚆 Thuis wonen & pendelen',
        income: [
          { label: 'Bijdrage ouders', amount: 150 },
          { label: 'Studentenjob', amount: 200 },
        ],
        expenses: [
          { label: 'Treinabonnement', amount: 55 },
          { label: 'Eten & snacks', amount: 80 },
          { label: 'Studiemateriaal', amount: 35 },
          { label: 'Abonnementen', amount: 28.97 },
          { label: 'Telefoon', amount: 15 },
          { label: 'Vrije tijd', amount: 40 },
          { label: 'Sparen', amount: 50, save: true },
        ],
        oneTime: [
          { label: 'Inschrijvingsgeld (1ste jaar)', amount: 1200 },
          { label: 'Laptop', amount: 750 },
        ],
        tip: 'Pendelen kost je elke dag ± 2 uur op de trein, maar je houdt ± €46 per maand over én spaart €50. Na een jaar is dat ruim €1.100 — genoeg voor een mooie reis.',
      },
    ],
    parentTip: '{name} verkende “Gaan studeren”. Goed moment om samen te bekijken wie wat betaalt: kot, inschrijvingsgeld, laptop.',
  },
  {
    id: 'studentenjob',
    emoji: '🍦',
    title: 'Een studentenjob',
    when: 'Dit schooljaar',
    intro: 'Stel: je gaat naast school in het weekend werken, net zoals je deze zomer deed bij IJssalon Gelato (± €11,46 bruto per uur).',
    keywords: ['studentenjob', 'jobstudent', 'weekendjob', 'vakantiejob', 'bijverdienen', 'geld verdienen', 'bijbaan', 'weekendwerk', 'werken als student', 'job'],
    topics: ['loon', 'budget'],
    xp: 40,
    checklist: [
      'Check je resterende studentenuren op Student@work',
      'Lees je contract: uurloon, uren en proefperiode',
      'Geef je rekeningnummer door voor je loon',
      'Controleer je loonstrook (2,71% solidariteitsbijdrage)',
      'Spreek met je ouders af of je zakgeld verandert',
      'Beslis vooraf hoeveel je spaart, bv. 30% van elk loon',
    ],
    options: [
      {
        id: '8u',
        label: '⏱️ 8 uur per week',
        income: [
          { label: 'Zakgeld', amount: 50 },
          { label: 'Studentenjob', amount: 386 },
        ],
        expenses: [
          { label: 'Abonnementen', amount: 28.97 },
          { label: 'Eten & snacks', amount: 30 },
          { label: 'Telefoon', amount: 10 },
          { label: 'Kleding (achteraf betalen)', amount: 13.32 },
          { label: 'Vrije tijd', amount: 60 },
          { label: 'Sparen', amount: 126, save: true },
        ],
        tip: 'Met 8 uur per week verdien je ± €386 netto per maand (en stop je met oppassen). Spaar je daarvan 30%, dan staat je Interrail-reis (nog €240) er al na ± 2 maanden.',
      },
      {
        id: '16u',
        label: '⏱️ 16 uur per week',
        income: [
          { label: 'Zakgeld', amount: 50 },
          { label: 'Studentenjob', amount: 772 },
        ],
        expenses: [
          { label: 'Abonnementen', amount: 28.97 },
          { label: 'Eten & snacks', amount: 40 },
          { label: 'Telefoon', amount: 10 },
          { label: 'Kleding (achteraf betalen)', amount: 13.32 },
          { label: 'Vervoer', amount: 20 },
          { label: 'Vrije tijd', amount: 90 },
          { label: 'Sparen', amount: 242, save: true },
        ],
        tip: '16 uur per week × 52 weken = 832 uur per jaar. Dat is meer dan het aantal studentenuren met lage bijdrage: daarboven betaal je gewone sociale bijdragen. En vergeet niet: school gaat voor!',
      },
    ],
    parentTip: '{name} bekeek “Een studentenjob”. Bespreek hoeveel uren naast school haalbaar zijn en wat er met het loon gebeurt.',
  },
  {
    id: 'werken',
    emoji: '💼',
    title: 'Mijn eerste job',
    when: 'Over ± 6 jaar',
    intro: 'Stel: je bent 22, afgestudeerd en je begint aan je eerste voltijdse job (± €3.000 bruto, ± €2.050 netto per maand). Van jobstudent naar werknemer: wat verandert er?',
    keywords: ['werken', 'eerste job', 'voltijds', 'fulltime', 'afstuderen', 'afgestudeerd', 'carriere', 'werknemer', 'bediende', 'salaris', 'loon', 'job'],
    topics: ['loon', 'budget'],
    xp: 40,
    checklist: [
      'Open een loonrekening en geef het nummer aan je werkgever',
      'Leer je loonstrook lezen: bruto − sociale bijdragen (13,07%) − belastingen = netto',
      'Laat je ziekenfonds weten dat je werkt (je bent niet meer “ten laste”)',
      'Bouw een noodbuffer op van 3 maanden vaste kosten',
      'Doe het jaar nadien je eerste belastingaangifte',
      'Overweeg pensioensparen (met fiscaal voordeel)',
    ],
    options: [
      {
        id: 'thuis',
        label: '🏡 Nog even thuis wonen',
        income: [{ label: 'Nettoloon', amount: 2050 }],
        expenses: [
          { label: 'Kostgeld thuis', amount: 250 },
          { label: 'Vervoer', amount: 60 },
          { label: 'Eten & snacks', amount: 150 },
          { label: 'Abonnementen', amount: 28.97 },
          { label: 'Telefoon', amount: 20 },
          { label: 'Vrije tijd', amount: 250 },
          { label: 'Pensioensparen', amount: 83 },
          { label: 'Sparen', amount: 800, save: true },
        ],
        oneTime: [],
        tip: 'Thuis wonen is dé kans om snel te sparen: met €800 per maand heb je na een jaar €9.600 — een stevige basis voor je eigen plek.',
      },
      {
        id: 'alleen',
        label: '🏢 Alleen gaan wonen',
        income: [{ label: 'Nettoloon', amount: 2050 }],
        expenses: [
          { label: 'Huur', amount: 800 },
          { label: 'Energie & water', amount: 120 },
          { label: 'Internet', amount: 40 },
          { label: 'Verzekeringen', amount: 35 },
          { label: 'Eten & snacks', amount: 300 },
          { label: 'Vervoer', amount: 60 },
          { label: 'Abonnementen', amount: 28.97 },
          { label: 'Telefoon', amount: 20 },
          { label: 'Vrije tijd', amount: 200 },
          { label: 'Pensioensparen', amount: 83 },
          { label: 'Sparen', amount: 250, save: true },
        ],
        oneTime: [
          { label: 'Huurwaarborg (3 maanden)', amount: 2400 },
          { label: 'Meubels & keuken', amount: 1500 },
        ],
        tip: 'Alleen wonen slorpt meer dan de helft van je loon op aan vaste kosten. Hou een buffer van 3 maanden kosten opzij (± €5.800) voor onverwachte uitgaven.',
      },
    ],
    parentTip: '{name} keek vooruit naar een eerste voltijdse job. Leuk om samen eens een echte loonstrook te bekijken!',
  },
  {
    id: 'huren',
    emoji: '🏠',
    title: 'Alleen gaan huren',
    when: 'Na je studies',
    intro: 'Stel: je hebt een job (± €2.050 netto) en je gaat een eigen plek huren. Een studio voor jou alleen, of samenhuizen met vrienden?',
    keywords: ['huren', 'huur', 'appartement', 'studio', 'alleen wonen', 'verhuizen', 'samenwonen', 'samenhuizen', 'eigen plek', 'woning', 'huurcontract', 'op mezelf'],
    topics: ['huur', 'budget'],
    xp: 40,
    checklist: [
      'Lees het huurcontract goed (de verhuurder moet het laten registreren)',
      'Huurwaarborg: max. 3 maanden huur, op een geblokkeerde rekening op jouw naam',
      'Sluit een brandverzekering af (verplicht voor huurders in Vlaanderen)',
      'Maak bij de start een plaatsbeschrijving, met foto’s',
      'Vraag energie, water en internet aan',
      'Geef je adreswijziging door aan de gemeente',
    ],
    options: [
      {
        id: 'studio',
        label: '🏢 Studio alleen (€750)',
        income: [{ label: 'Nettoloon', amount: 2050 }],
        expenses: [
          { label: 'Huur', amount: 750 },
          { label: 'Energie & water', amount: 110 },
          { label: 'Internet', amount: 40 },
          { label: 'Brandverzekering', amount: 12 },
          { label: 'Eten & snacks', amount: 280 },
          { label: 'Vervoer', amount: 60 },
          { label: 'Abonnementen', amount: 28.97 },
          { label: 'Telefoon', amount: 20 },
          { label: 'Vrije tijd', amount: 200 },
          { label: 'Sparen', amount: 300, save: true },
        ],
        oneTime: [
          { label: 'Huurwaarborg (3 maanden)', amount: 2250 },
          { label: 'Eerste maand huur', amount: 750 },
          { label: 'Meubels & keuken', amount: 1200 },
          { label: 'Verhuis', amount: 150 },
        ],
        tip: 'Nog vóór je de sleutel krijgt, heb je al ± €4.350 nodig: waarborg, eerste huur en meubels. Begin dus ruim op voorhand te sparen.',
      },
      {
        id: 'samen',
        label: '👯 Samenhuizen (€450 p.p.)',
        income: [{ label: 'Nettoloon', amount: 2050 }],
        expenses: [
          { label: 'Huur', amount: 450 },
          { label: 'Energie & water', amount: 60 },
          { label: 'Internet', amount: 15 },
          { label: 'Brandverzekering', amount: 8 },
          { label: 'Eten & snacks', amount: 250 },
          { label: 'Vervoer', amount: 60 },
          { label: 'Abonnementen', amount: 28.97 },
          { label: 'Telefoon', amount: 20 },
          { label: 'Vrije tijd', amount: 220 },
          { label: 'Sparen', amount: 500, save: true },
        ],
        oneTime: [
          { label: 'Huurwaarborg (3 maanden)', amount: 1350 },
          { label: 'Eerste maand huur', amount: 450 },
          { label: 'Meubels (gedeeld)', amount: 500 },
        ],
        tip: 'Samenhuizen scheelt je ± €400 per maand. Maak wel duidelijke afspraken: wie betaalt wat, en wat als iemand vertrekt?',
      },
    ],
    parentTip: '{name} bekeek “Alleen gaan huren”. Vertel eens hoe het was toen jij voor het eerst ging huren!',
  },
  {
    id: 'vakantie',
    emoji: '✈️',
    title: 'Op vakantie',
    when: 'Volgende zomer',
    intro: 'Volgende zomer wil je met vrienden op reis. Je spaardoel “Interrail met vrienden” staat al op €210 van €450. Welke reis past in je budget?',
    keywords: ['vakantie', 'reis', 'reizen', 'op reis', 'interrail', 'citytrip', 'zomer', 'festival', 'weekendje weg', 'zee', 'buitenland', 'trip'],
    topics: ['sparen', 'betalen'],
    xp: 40,
    alreadySaved: 210,
    showSavingTime: true,
    checklist: [
      'Maak een reisbudget: vervoer, slapen, eten en activiteiten',
      'Koppel je spaardoel aan een automatische overschrijving',
      'Check of je een reisbijstandsverzekering hebt (vaak via je ouders)',
      'Vraag je Europese ziekteverzekeringskaart aan via je ziekenfonds',
      'Betalen in het buitenland: in de eurozone kost je kaart meestal niets extra, daarbuiten let je op kosten',
      'Hou een noodpotje apart (bv. €50)',
    ],
    options: [
      {
        id: 'interrail',
        label: '🚆 Interrail 1 week (€450)',
        income: LENA_NOW.income,
        expenses: [
          { label: 'Abonnementen', amount: 18.98 },
          { label: 'Eten & snacks', amount: 8.6 },
          { label: 'Telefoon', amount: 10 },
          { label: 'Sparen', amount: 40, save: true },
        ],
        oneTime: [
          { label: 'Interrail-pas (4 reisdagen)', amount: 190 },
          { label: 'Hostels (6 nachten)', amount: 150 },
          { label: 'Eten & drinken', amount: 80 },
          { label: 'Activiteiten', amount: 30 },
        ],
        tip: 'Schrap Disney+ (€9,99), haal €10 van je snackgeld en gebruik de €13,32 die vrijkomt zodra “achteraf betalen” in oktober afgelost is: zo spaar je €40 per maand in plaats van €10, en haal je Interrail in 6 maanden in plaats van 24.',
      },
      {
        id: 'zee',
        label: '🏖️ Weekje aan zee (€250)',
        income: LENA_NOW.income,
        expenses: LENA_NOW.expenses,
        oneTime: [
          { label: 'Trein heen & terug', amount: 30 },
          { label: 'Jeugdherberg (5 nachten)', amount: 150 },
          { label: 'Eten & drinken', amount: 55 },
          { label: 'Fietsverhuur', amount: 15 },
        ],
        tip: 'Je hebt al €210, dus je komt maar €40 tekort: aan je huidige tempo is dat 4 maanden. Je hoeft niets te veranderen!',
      },
      {
        id: 'ver',
        label: '🌴 Verre reis (€1.400)',
        income: LENA_NOW.income,
        expenses: [
          { label: 'Abonnementen', amount: 18.98 },
          { label: 'Eten & snacks', amount: 8.6 },
          { label: 'Telefoon', amount: 10 },
          { label: 'Sparen', amount: 40, save: true },
        ],
        oneTime: [
          { label: 'Vliegtuigticket', amount: 750 },
          { label: 'Verblijf', amount: 400 },
          { label: 'Eten & drinken', amount: 150 },
          { label: 'Activiteiten', amount: 100 },
        ],
        tip: 'Met €40 per maand duurt het ± 30 maanden. Met een studentenjob van 8 uur per week (30% sparen) lukt het al in ± 10 maanden — speel dat scenario ook eens!',
      },
    ],
    parentTip: '{name} plant een reis met vrienden. Bespreek samen de reisverzekering en hoeveel noodgeld er mee moet.',
  },
  {
    id: 'beleggen',
    emoji: '📈',
    title: 'Beginnen beleggen',
    when: 'Vanaf nu, samen met je ouders',
    intro: 'Stel: je zet elke maand een klein bedrag opzij voor later. Laat je het op je spaarrekening staan, of beleg je het in een fonds met honderden bedrijven?',
    keywords: ['beleggen', 'aandelen', 'aandeel', 'fonds', 'beurs', 'investeren', 'crypto', 'bitcoin', 'etf', 'rendement', 'rijk worden'],
    topics: ['beleggen', 'sparen'],
    xp: 40,
    growth: { years: 10, savingsRate: 0.015, investRate: 0.05, badRate: -0.02, goodRate: 0.08 },
    checklist: [
      'Zorg eerst voor een noodbuffer op je spaarrekening',
      'Beleg enkel geld dat je 5 à 10 jaar kan missen',
      'Spreid: liever een fonds met honderden bedrijven dan één aandeel',
      'Let op de kosten: instapkosten, beheerkosten en taksen',
      'Onder de 18? Dan beleg je samen met je ouders',
      'Wantrouw “snel rijk”-beloftes en crypto-hypes op sociale media',
    ],
    options: [
      {
        id: '10',
        label: '€10 per maand',
        monthly: 10,
        income: LENA_NOW.income,
        expenses: [
          { label: 'Abonnementen', amount: 18.98 },
          { label: 'Eten & snacks', amount: 18.6 },
          { label: 'Telefoon', amount: 10 },
          { label: 'Kleding (achteraf betalen)', amount: 13.32 },
          { label: 'Sparen', amount: 10, save: true },
          { label: 'Beleggen', amount: 10 },
        ],
        tip: 'Schrap Disney+ en je belegt €10 per maand zonder dat je iets anders hoeft te missen.',
      },
      {
        id: '20',
        label: '€20 per maand',
        monthly: 20,
        income: LENA_NOW.income,
        expenses: [
          { label: 'Abonnementen', amount: 18.98 },
          { label: 'Eten & snacks', amount: 8.6 },
          { label: 'Telefoon', amount: 10 },
          { label: 'Kleding (achteraf betalen)', amount: 13.32 },
          { label: 'Sparen', amount: 10, save: true },
          { label: 'Beleggen', amount: 20 },
        ],
        tip: 'Schrap Disney+ en €10 snackgeld: zo beleg je €20 per maand. Na 10 jaar heb je zelf €2.400 ingelegd.',
      },
      {
        id: '40',
        label: '€40 per maand (met studentenjob)',
        monthly: 40,
        income: [
          { label: 'Zakgeld', amount: 50 },
          { label: 'Studentenjob', amount: 386 },
        ],
        expenses: [
          { label: 'Abonnementen', amount: 28.97 },
          { label: 'Eten & snacks', amount: 30 },
          { label: 'Telefoon', amount: 10 },
          { label: 'Kleding (achteraf betalen)', amount: 13.32 },
          { label: 'Vrije tijd', amount: 60 },
          { label: 'Sparen', amount: 86, save: true },
          { label: 'Beleggen', amount: 40 },
        ],
        tip: 'Met een studentenjob van 8 uur per week zet je 30% van je loon opzij: €40 beleggen en de rest op je spaarrekening.',
      },
    ],
    parentTip: '{name} verkende “Beginnen beleggen”. Misschien samen een klein bedrag leren beleggen en de kosten vergelijken?',
  },
];
